### ISSUE TITLE
Warning notification being spawned every time the IDE opens

### ISSUE THREAD

**Issue by panckreous** [ADMARIl/halcyon-jetbrains#13]
Hey Andrew, thanks for fixing #11 so quickly. I think one more piece slipped through - if I have the plugin for the theme enabled at all it spawns this event message every time I open the IDE. It's minor, but any chance on removing it?

![Screen Shot 2021-06-22 at 6 35 45 AM](https://user-images.githubusercontent.com/208280/122934427-5f888d00-d324-11eb-93e3-76d2713c069a.png)
![Screen Shot 2021-06-22 at 6 36 26 AM](https://user-images.githubusercontent.com/208280/122934432-60b9ba00-d324-11eb-9f62-b8dd0b5c2486.png)

thanks again

**Comment by ADMARIl** [comment]
Sure I can remove it

**Comment by ADMARIl** [comment]
Just published a fix in [2.1.2](https://github.com/ADMARIl/halcyon-jetbrains/releases/tag/v2.1.2). Sorry for the delay complete forgot about this
