### ISSUE TITLE
Disappeared theme in Appearance new version Android Studio

### ISSUE THREAD

**Issue by atname** [ADMARIl/halcyon-jetbrains#14]
In Editor Settings have color scheme HalcyonTheme but in studio theme no. 

Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 26, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3000M
Cores: 8
Registry: external.system.auto.import.disabled=true, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, Rider UI Theme Pack, com.ADMARIl.halcyon-jetbrains, com.markskelton.one-dark-theme, net.antelle.intellij-xcode-dark-theme, Dart, org.jetbrains.kotlin, io.flutter, com.jetbrains.edu, izhangzhihao.rainbow.brackets

p.s your theme is the best)

**Comment by ADMARIl** [comment]
To confirm, you don't see the option for choosing the theme in the appearance menu? Please confirm what you have here; File → Settings → Appearance & Behavior → Appearance → Theme

**Comment by atname** [comment]
Yeah, here screenshots to confirm. 
https://pastenow.ru/bbe2493ca7a5b0bf00c98e5560456f5b - Installed plugin
https://pastenow.ru/3fc826c9dd2b1c0193f141e74a5fa4a0 - Themes
https://pastenow.ru/8f5587ca65208af57bfa6908be73c020 - color scheme

**Comment by nikunjparadva** [comment]
## Here is the Solution
https://stackoverflow.com/a/68599712/5773037

**Comment by ADMARIl** [comment]
Seems like an issue with android studio itself so I’m closing this issue
