### ISSUE TITLE
2021.3 EAP support

### ISSUE THREAD

**Issue by panckreous** [ADMARIl/halcyon-jetbrains#15]
Any chance you can update with 2021.3 EAP support when you get a chance?

**Comment by ADMARIl** [comment]
I’ll take a look

**Comment by Sijoma** [comment]
Whoop whoop! 🚀

**Comment by ADMARIl** [comment]
The release fixing this issue has been submitted to JetBrains for review. I'll update once it's approved

**Comment by panckreous** [comment]
Thanks, I really appreciate

**Comment by ADMARIl** [comment]
2.2.0 is now public https://plugins.jetbrains.com/plugin/14093-halcyon-theme/versions/stable/162633
