### ISSUE TITLE
Halcyon no longer compatible with latest IDE build

### ISSUE THREAD

**Issue by QuantuMope** [ADMARIl/halcyon-jetbrains#16]
Hello, will halcyon be updated to be available for the latest IDE build?
I was devastated to see my favorite theme being no longer compatible.

Thanks so much for the great theme!

**Comment by Sijoma** [comment]
+1 . It is such a nice theme.

**Comment by james-becker** [comment]
+1. I've been using this theme for 2 straight years. Sadly, since I upgraded to RubyMine 2021.3.1, it isn't working. I feel like an astronaut on mars without a helmet.

**Comment by ADMARIl** [comment]
Duplicates #15
