### ISSUE TITLE
The theme does not support the latest version of Intellij

### ISSUE THREAD

**Issue by AHED200** [ADMARIl/halcyon-jetbrains#20]
Now Halcyon does not support the latest version of Intellij.
Intellij version information: Build #IC-222.3345.118, built on July 26, 2022

![idea64_CG9dlvMWvU](https://user-images.githubusercontent.com/78029038/181273824-2ff19b06-afdc-44f9-8700-10b74d6c48fd.png)

**Comment by shostakalex** [comment]
Yes, please @ADMARIl , can you update your the very best theme for intellij? :)

**Comment by ADMARIl** [comment]
Sure I’ll take a look ~~this weekend~~

**Comment by bartiiix** [comment]
@ADMARIl I'm also waiting

**Comment by digeomel** [comment]
Would love to get an update of this too, this is the best theme for IntelliJ by far!

**Comment by Sijoma** [comment]
Are there any steps that are needed for the update? Is it a major change everytime? Maybe we can document it and help out with maintaing the updates. 😅

**Comment by rostislaved** [comment]
also waiting

**Comment by ADMARIl** [comment]
v2.2.1 has been submitted to JetBrains for review and will be available publically once their review is complete. If you need the update urgently, you can grab the release here: https://github.com/ADMARIl/halcyon-jetbrains/releases/tag/v2.2.1

Additionally, I do apologize for the wait in getting this fixed. Unfortunately, I no longer use JetBrains IDEs in my day-to-day work so I don't have as much time to keep this plugin updated; however, I still do update occasionally!

**Comment by ADMARIl** [comment]
2.2.1 is now available on the marketplace

**Comment by bartiiix** [comment]
[image: image.png]

When update? <3

śr., 21 wrz 2022 o 00:07 Andrew Ingson ***@***.***>
napisał(a):

**Comment by bartiiix** [comment]
[image: image.png]
Hi, please update

czw., 22 gru 2022 o 15:20 Bartosz Czerwonka ***@***.***>
napisał(a):
