### ISSUE TITLE
not compatible with new IntelliJ IDEA 2023.1

### ISSUE THREAD

**Issue by SlenderBear** [ADMARIl/halcyon-jetbrains#31]
This message appears since last IDEA update:
Plugin 'Halcyon Theme' (version '2.3.1') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is IC-231.8109.175

**Comment by springmonster** [comment]
@SlenderBear, you can download the jar and install plugin from disk.
https://github.com/springmonster/halcyon-jetbrains/blob/feature/ic-2023.1/libs/halcyon-jetbrains-2.3.2.jar

**Comment by rostislaved** [comment]
Why is it closed? https://plugins.jetbrains.com/plugin/14093-halcyon-theme says:
`Not compatible with the version of your running IDE (GoLand 2023.1)`
